[package]
name = "simple-path-match"
version = "0.1.0"
edition = "2021"
authors = ["Francis Russell <francis@unchartedbackwaters.co.uk>"]
readme = "README.md"
license = "BSD-3-Clause"
description = "Trivial path matching"

[dependencies]
itertools = "0.10.5"
thiserror = "1.0.37"
