[package]
name = "simple-path-match"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
regex = { version = "1.7.0", default-features = false, features = [ "std" ] }
thiserror = "1.0.37"
